// Replace this sample profile and the concept projects with your own work.
export const profile = {
  name: "Nuttanon Ungkachan",
  role: "Full-Stack Software Engineer",
  location: "Bangkok, Thailand",
  email: "nuttanon.u@proton.me",
  introduction:
    "An software engineer who obsess in building system with millions of transactions a day in entreprise company. Has experience in working with software house and well-known first bank of Thailand.",
  stack: [
    "Angular",
    "NextJS",
    "Zoral Platform",
    "NodeJS(Express)",
    "Java Springboot",
    "Go (GIN)",
    "SQL (POSGRESQL, MYSQL)",
    "GraphQL",
    "Convex",
    "Tailwind CSS",
    "ShadCN",
    "Git",
  ],
};

export const projects = [
  { slug: "ias", name: "Internal Audit System", category: "Web Application", year: "2023", type: "Company Audit's Backoffice system", theme: "ias", tagline: "Audit modernize produre replacing manual paper process.", description: "Internal Audit System (IAS) is an Angular + Java Springboot and MySQL project which built for modernize the audit workflow from doing tons of paperwork and excel to using web application which replaces manual paperwork and spreadsheet-based processes with role-based access, structured records, and traceable activity logs.", responsibility: "My assignment in this project, as a freshly new software engineer, contributed to the application’s frontend and backend features using Angular, Spring Boot, and MySQL which included implementing assigned workflow screens, connecting them to backend services, handling role-based behavior and email notification when user's submitting task to their next level, and resolving issues found during review and testing.", challenge: "This is the first project in my career of Software engineer which have a really high learning curve from using Angular 14, Java Springboot and MySQL to built this system using only the classroom knowledge is very challenging and I'm still a novice with problem solving skill in real world problem.", approach: "When there's something I have to do the first time, i'm always pouring my effort and time into it since this is the starting point of my career. I'm more than willing to put my effort and time into learning the real world entreprise system building with the help of senior engineer at the company and try building it on my own with the task given, learning from my mistake and doing it better.", stack: ["Angular 14", "Tailwind CSS", "Java Springboot", "MySQL"] },
  { slug: "rfs", name: "Referral System", category: "Web Application", year: "2024", type: "Healthcare Patient Transfer System", tagline: "A hospital patient referral system.", description: "Referral System (RFS) is a demo pitching project built for communicating patient referral between multiple hospital with healthcare history and replacing current manual procedure using an referral letter which require patient to travel to their assigned hospital for further procedure. RFS was built using NextJS, ChakraUI, Prisma, Neon Database (Posgresql), integrated WorkOS authentication and enforced role-based permissions.", responsibility: "My task in this demo project was to built the prototype as a full-stack Next.js application. I worked on the refferal flows API, refferal page frontend and designing system SQL database schema, and role-base authorization for each flows.", challenge: "This is my first time to experience building an React Application with NextJS and since this is a pitching demo project, I have to go all out with this system's demo with my knowledge and skill from IAS project during the cooperative study program", approach: "Since I'm worked on angular before, building application with react is very similar dueto my knowledge with Angular I can transfer it to React (NextJS) smoothly except the NextJS backend function is somewhat different since its use type script for backend too instead of java springboot but the core concept is still the same which make my development really fast.", stack: ["NextJS", "ChakraUI", "Prisma (SQL ORM)","Neon (Posgresql)", "WorkOS"] },
  { slug: "nleads", name: "Nextgen Lendings", category: "Web Application", year: "2024", type: "Banking Teller's System", theme: "daylight", tagline: "A lending system replacement project", responsibility: "This project is when I get to build the fullstack feature for the entreprise which has to scale with multiple millions of transaction a day. My work here include frontend page, backend API feature, Application Internal Report, Batch Job with Azure Data Factory, backend performance tuning issue and other feature issue", description: "This project was built to replace and modernize the legacy application which going to be obsolete soon for bank teller's employees. This system was built with Zoral Platform, an Lowcode platform, that frontend are based on React and MUI and backend is based on NodeJS (Express) with graphql for database transaction.", challenge: "The stack (Zoral Platform) is really nieches since its a lowcode with very few document about. It's very hard when there's syntax error or somethings break you can only ask the Zoral's support team to investigate which make the development process slower than the plan than using conventional framework.", approach: "The Zoral Platform is some what hard to use at first but since I had worked with Angular, NextJS before which I can compare this stack to them and it's start making sense with zoral platform is an React/NodeJS wrapper so I can speed up my development with Zoral Platform by knowing NextJS, Angular NodeJS work under the hood of the platform.", stack: ["Zoral Platform", "NodeJS (Express)", "MUI", "GraphQL", "Posgresql"] },
  { slug: "salarycal", name: "Salary Cal", category: "Web Application", year: "2026", type: "Company Founder's Backoffice System", theme: "daylight", tagline: "An internal salary calculation system for private company owner.", responsibility: "Since this is my family's company application. All the task in this application is on me from design the system architecture, authentication, salary calculation page, calculation formular, export monthly data to xlsx, convex database integration role base authorization, backoffice page for configuring calculartion formular and deployment", description: "An web app for calculate each employee salary that're work in film company built using NextJS/ Convex Database with BetterAuth providing role base application with oauth2 implemented. And with convex database, the application provide an subscription feature to database with reactive queries keep the interface updated without manually managing WebSocket connections without using graphql.", challenge: "This project is built using a new techstack for experimental which I haven't been used before with convex a Document-Relational Database and since the scope for the application is not really big but it still some work for a solo engineer since I have gather requirement, design, implement and deploy all by myself.", approach: "Nothing is too hard to learn or try, I'm really obsess with new techstack that has some unique idea and with LLM help, I can studying new tech try building new system more effient than ever. With this project I'm start implementing small feature first such as calculation system and then enhancing it with reference calculation formualr from a database config, implement backoffice menu for configuring calcualtion formular and then start implementing authentication system and role-base access control for only authorize email in whitelist to be able to access to this application.", stack: ["NextJS", "Shadcn/ui", "TailwindCSS", "Convex", "Vercel"] },
];

