// Replace this sample profile and the concept projects with your own work.
export const profile = {
  name: "Nuttanon Ungkachan",
  role: "Full-Stack Software Engineer",
  location: "Bangkok, Thailand",
  email: "nuttanon.u@proton.me",
  introduction: "An software engineer who obsess in building system with millions of transactions a day in entreprise company. Has experience in working with software house and well-known first bank of Thailand.",
  stack: ["Angular", "NextJS", "Zoral Platform", "NodeJS(Express)", "Java Springboot", "Go (GIN)", "SQL (POSGRESQL, MYSQL)", "GraphQL", "Convex", "Tailwind CSS", "ShadCN"]
};

export const projects = [
  { slug: "ias", name: "Internal Audit System", category: "Web Application", year: "2023", type: "Backoffice system", theme: "ias", tagline: "Audit modernize workflow pipeline.", description: "A workflow concept for managing internal audits, organizing evidence, and tracking reviews in one application.", challenge: "This is the first project in my career of Software engineer which have a really high learning curve from using Angular 14, Java Springboot and MySQL to built this system.", approach: "", stack: ["Angular 14", "Tailwind CSS", "Java Springboot", "MySQL"] },
  { slug: "rfs", name: "Referral System", category: "Web Application", year: "2024", type: "Backoffice System", theme: "rooted", tagline: "A foundation for growing data.", description: "A database architecture study exploring how caching, indexing, and read replicas can support an application as its workload grows.", challenge: "Scale read-heavy workloads while keeping consistency requirements and operational complexity visible.", approach: "Start with query plans and indexing, cache suitable reads, and consider replication only when measurements justify it.", stack: ["SQL", "Caching", "Read Replicas"] },
  { slug: "nleads", name: "Nextgen Lendings", category: "Web Application", year: "2024", type: "Banking Teller's System", theme: "daylight", tagline: "An lending system replacement project which enhance and modernize the legacy application which going to be obsolete soon for bank teller's employees. This system was built with Zoral Platform, an Lowcode platform, that frontend are based on React and MUI and backend is based on NodeJS (Express) with graphql for database transaction", description: "A personal planning app concept built around focus. A clear daily overview brings tasks and small moments of progress into one thoughtful workspace.", challenge: "Help people see what matters today without overwhelming them with every future task.", approach: "A focused daily view, clear visual hierarchy, and small progress cues make planning feel manageable.", stack: ["Zoral Platform", "NodeJS (Express)", "MUI", "GraphQL", "Posgresql"] },
  { slug: "salarycal", name: "Salary Cal", category: "Web Application", year: "2026", type: "Backoffice System", theme: "daylight", tagline: "An internal salary calculation system for private company owner.", description: "An web app for calculate each employee salary that're work in film company built using NextJS/ Convex Database with BetterAuth providing role base application with oauth2 implemented. And with convex database, the application provide an subscription feature to database without using websocket like graphql", challenge: "This project is built using a new techstack for experimental which I haven't been used before with convex a Document-Relational Database.", approach: "Nothing is too hard to learn and I really obsess with new techstack that has some unique idea and with LLM help, I can studying new tech try building new system more effient than ever", stack: ["NextJS", "Shadcn/ui", "TailwindCSS", "Convex"] },
];

